version: '3.8'
services:
  selenoid-cm:
    image: "aerokube/cm:latest-release"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/root/.aerokube/selenoid"
    environment:
      OVERRIDE_HOME: "$PWD/config/"
    command: [ "selenoid", "configure", "--vnc", "--tmpfs", "128" ]
  selenoid:
    network_mode: bridge
    image: "aerokube/selenoid:latest-release"
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/output/video:/opt/selenoid/video"
      - "$PWD/output/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/opt"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    ports:
      - "8888:8080"
